<?xml version="1.0"?>
<robot name="my_mobile" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="wheel_separation" value="0.1"/>
    <xacro:property name="wheel_diameter" value="0.06"/>

    <link name="base_footprint"/>

    <joint name="base_link_fixed_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_diameter/2}" rpy="0 0 0"/>
    </joint>

	<link name="base_link">
		<visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find pinky_description)/meshes/visual/base_link.dae" scale="1 1 1"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find pinky_description)/meshes/collision/base_link.stl" scale="1 1 1"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="-0.02 0 0.028" rpy="0 0 0"/>
            <mass value="2.0"/>
            <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
        </inertial>
	</link>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_separation/2} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find pinky_description)/meshes/visual/wheel.dae" scale="1 1 1"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find pinky_description)/meshes/collision/wheel.stl" scale="1 1 1"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.2"/>
            <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
        </inertial>
    </link>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-1 * wheel_separation/2} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find pinky_description)/meshes/visual/wheel.dae" scale="1 1 1"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find pinky_description)/meshes/collision/wheel.stl" scale="1 1 1"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.2"/>
            <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
        </inertial>
    </link>

    <link name="ul_sensor_mount">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find pinky_description)/meshes/visual/ul_sensor.dae" scale="1 1 1"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find pinky_description)/meshes/collision/ul_sensor.stl" scale="1 1 1"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.005 0 0.013" rpy="0 0 0"/>
            <mass value="0.050000"/>
            <inertia ixx="0.000005" ixy="0" ixz="-0.000001" iyy="0.000004" iyz="0" izz="0.000003"/>
        </inertial>
    </link>

    <joint name="ul_sensor_mount_fixed_joint" type="fixed">
        <parent link="base_link"/>
        <child link="ul_sensor_mount"/>
        <origin xyz="0.038 -0.002 -0.0035" rpy="0 0 0"/>
    </joint>

    <link name="ul_sensor_link"/>

    <joint name="ul_sensor_link_fixed_joint" type="fixed">
        <parent link="ul_sensor_mount"/>
        <child link="ul_sensor_link"/>
        <origin xyz="0.01 0 0" rpy="0 0 0"/>
    </joint>

    <link name="front_camera_mount">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find pinky_description)/meshes/visual/camera.dae" scale="1 1 1"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find pinky_description)/meshes/collision/camera.stl" scale="1 1 1"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.005 0 0.013" rpy="0 0 0"/>
            <mass value="0.050000"/>
            <inertia ixx="0.000005" ixy="0" ixz="-0.000001" iyy="0.000004" iyz="0" izz="0.000003"/>
        </inertial>
    </link>

    <joint name="front_camera_mount_fixed_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_camera_mount"/>
        <origin xyz="0.05 -0.001 0.028" rpy="0 0 0"/>
    </joint>

    <link name="camera_link"/>

    <joint name="camera_link_fixed_joint" type="fixed">
        <parent link="front_camera_mount"/>
        <child link="camera_link"/>
        <origin xyz="0.001 0 0.003" rpy="0 ${pi/2} 0"/>
    </joint>

    <link name="rplidar_lidar_mount">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find pinky_description)/meshes/visual/lidar.dae" scale="1 1 1"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="file://$(find pinky_description)/meshes/collision/lidar.stl" scale="1 1 1"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.007 0 0.025" rpy="0 0 0"/>
            <mass value="0.110"/>
            <inertia ixx="0.000058" ixy="0" ixz="0.000005" iyy="0.000099" iyz="0" izz="0.000103"/>
        </inertial>
    </link>

    <joint name="lidar_mount_fixed_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rplidar_lidar_mount"/>
        <origin xyz="0 0 0.042" rpy="0 0 0"/>
    </joint>

    <link name="laser_link"/>

    <joint name="laser_link_fixed_joint" type="fixed">
        <parent link="rplidar_lidar_mount"/>
        <child link="laser_link"/>
        <origin xyz="0.0 0 0.03" rpy="0 0 ${pi}"/>
    </joint>
</robot>
